Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,13 +17,19 @@ jobs:
 
       - name: Set up Keenetic SDK
         run: |
-          git clone --depth 1 --branch 3.07.C.4.0-2 https://github.com/keenetic/keenetic-sdk.git
+          git clone --depth 1 --branch 3.08 https://github.com/keenetic/keenetic-sdk.git
           mkdir -p keenetic-sdk/package/keenetic-huawei-integration
           find . -maxdepth 1 -not -path "./keenetic-sdk" -not -path . -not -path "./.git" -exec cp -r {} keenetic-sdk/package/keenetic-huawei-integration/ \;
           cd keenetic-sdk
           sudo apt update
           sudo apt install -y build-essential git python3 attr bc curl gawk libhtml-parser-perl libjson-perl libncurses-dev libssl-dev libxml-libxml-perl subversion unzip zlib1g-dev make gcc lzip gperf protobuf-c-compiler
-          ./configure.sh --arch mipsel
+          echo "Running configure.sh..."
+          ./configure.sh --arch mipsel || { echo "configure.sh failed"; exit 1; }
+          if [ ! -f .config ]; then
+            echo ".config file not created!"
+            exit 1
+          fi
+          echo ".config file created successfully"
 
       - name: Build OPKG package
         run: |
