Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,9 +25,9 @@ jobs:
           sudo apt install -y build-essential git python3 attr bc curl gawk libhtml-parser-perl libjson-perl libncurses-dev libssl-dev libxml-libxml-perl subversion unzip zlib1g-dev make gcc lzip gperf protobuf-c-compiler flex bison
           echo "Listing available devices..."
           ./configure.sh -l
-          echo "Running configure.sh for all..."
+          echo "Running configure.sh for KN-2311..."
           ./configure.sh KN-2311 || {
-            echo "configure.sh for all failed, trying preset 'all'..."
+            echo "configure.sh for KN-2311 failed, trying preset 'all'..."
             ./configure.sh -p all || { echo "configure.sh with preset 'all' failed"; exit 1; }
           }
           if [ ! -f .config ]; then
@@ -39,7 +39,11 @@ jobs:
       - name: Build OPKG package
         run: |
           cd keenetic-sdk
-          make package/huawei-integration/clean
+          echo "[*] Синхронизация .config..."
+          make defconfig
+          echo "[*] Очистка пакета huawei-integration..."
+          make package/huawei-integration/clean || true
+          echo "[*] Сборка пакета huawei-integration..."
           make package/huawei-integration/compile V=s
 
       - name: Upload artifact
