Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,8 +25,8 @@ jobs:
           sudo apt install -y build-essential git python3 attr bc curl gawk libhtml-parser-perl libjson-perl libncurses-dev libssl-dev libxml-libxml-perl subversion unzip zlib1g-dev make gcc lzip gperf protobuf-c-compiler flex bison
           echo "Listing available devices..."
           ./configure.sh -l
-          echo "Running configure.sh for kn-2311..."
-          ./configure.sh kn-2311 || { echo "configure.sh failed"; exit 1; }
+          echo "Running configure.sh for kn-2310..."
+          ./configure.sh kn-2310 || { echo "configure.sh failed"; exit 1; }
           if [ ! -f .config ]; then
             echo ".config file not created!"
             exit 1
